name: .NET Core GitHub NuGet feed
on:
  push:
    branches:
      - main
  workflow_dispatch:
    logLevel:
      description: 'Log level'
      required: true
      derault: 'warning'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Version
      run: echo "PACKAGE_VERSION=${{ env.VERSION }}.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
      - name: Display Version
      run: echo $PACKAGE_VERSION    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release 
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Create artifacts folder
      run: |
        mkdir "$GITHUB_WORKSPACE/artifacts"
        mkdir "$GITHUB_WORKSPACE/artifacts/Toolkit"
    - name: Publish Toolkit
      run: dotnet publish Toolkit/Toolkit.csproj --configuration Release --output "$GITHUB_WORKSPACE/artifacts/Toolkit"

    - name: Pack Toolkit
      run: |
        dotnet pack Toolkit/Toolkit.csproj --configuration Release --include-source --include-symbols --no-build --output "$GITHUB_WORKSPACE/artifacts/Toolkit" -p:PackageVersion=$PACKAGE_VERSION

    - name: Setup .NET Core for publish
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
    - name: Add source
      run: |
        dotnet nuget add source "https://nuget.pkg.github.com/bthidev/index.json" --username bthidev --password ${{ secrets.pat_token }} --store-password-in-clear-text --name github 
    - name: Push packages to GitHub Packages NuGet feed
      run: |
        dotnet nuget push "$GITHUB_WORKSPACE/artifacts/Toolkit/Toolkit.$PACKAGE_VERSION.nupkg"  --api-key ${{ secrets.pat_token }} --source "github"